import { units } from './curriculum.js';
import { learningState, learningMetrics, recommendUnits } from './learning-engine.js';

export function renderLearning(state, language, e, query = '') {
  const pt = language === 'pt-BR', t = (en, br) => e(pt ? br : en), loc = value => e(value[pt ? 'pt-BR' : 'en']);
  const learning = learningState(state), metrics = learningMetrics(state), active = learning.active;
  const modeName = mode => ({ recognition: t('Recognition · 2 checks', 'Reconhecimento · 2 questões'), guided: t('Guided · 5 activities', 'Guiado · 5 atividades'), applied: t('Applied · 8 activities', 'Aplicação · 8 atividades') })[mode];
  const button = (action, text, extra = '', style = 'primary') => `<button type="button" class="button ${style}" data-action="learn-${action}" ${extra}>${text}</button>`;
  const audio = unit => `<div class="learning-audio"><audio controls preload="none" aria-label="${t('English example audio', 'Áudio do exemplo em inglês')}"><source src="./src/assets/audio/${unit.id}.mp3" type="audio/mpeg"></audio><div class="form-actions">${[0.75, 1].map(speed => button('speed', e(`${speed}×`), `data-speed="${speed}"`, 'subtle')).join('')}</div><small>${t('Synthetic voice. Listen, pause and repeat at your own pace; no pronunciation score.', 'Voz sintética. Ouça, pause e repita no seu ritmo; sem nota de pronúncia.')}</small></div>`;
  const title = `<div class="page-top"><div><p class="eyebrow">${t('LEARN · RETRIEVE · APPLY', 'APRENDA · RECUPERE · APLIQUE')}</p><h1>${t('Your learning path', 'Sua trilha de aprendizagem')}</h1><p>${t('Short explanations. Useful English. One step at a time.', 'Explicações curtas. Inglês útil. Um passo por vez.')}</p></div><div class="language-switch"><button data-language="en" aria-pressed="${!pt}">EN</button><button data-language="pt-BR" aria-pressed="${pt}">PT-BR</button></div></div>`;
  if (active) {
    const question = active.questions[active.index], unit = units.find(u => u.id === question.unitId);
    const progress = `<div class="progress-top"><span>${loc(unit.title)}</span><span>${active.index + 1} / ${active.questions.length}</span></div><progress value="${active.index}" max="${active.questions.length}" aria-label="${t('Activities completed', 'Atividades concluídas')}"></progress>`;
    const exit = `<div class="form-actions"><a class="button subtle" href="#overview">${t('Pause and keep progress', 'Pausar e manter progresso')}</a>${button('discard', t('Discard lesson', 'Descartar lição'), '', 'subtle')}</div>`;
    if (active.phase === 'lesson') return `${title}<section class="panel learning-panel">${progress}<span class="eyebrow">${t('BEFORE THE EXERCISES', 'ANTES DOS EXERCÍCIOS')}</span><h2>${loc(unit.title)}</h2><p>${loc(unit.explanation)}</p><div class="worked-example"><strong>${t('Notice the example', 'Observe o exemplo')}</strong><p lang="en">${e(unit.example)}</p>${pt ? `<p>${e(unit.meaning)}</p>` : ''}</div>${audio(unit)}<details><summary>${t('Read the transcript', 'Ler a transcrição')}</summary><p lang="en">${e(unit.example)}</p></details>${unit.id === 'introductions' ? `<details><summary>${t('Watch the captioned explanation', 'Assistir à explicação com legendas')}</summary><video controls preload="none" aria-label="${t('Introduction example with captions', 'Exemplo de apresentação com legendas')}"><source src="./src/assets/video/introductions.mp4" type="video/mp4"><track kind="captions" src="./src/assets/video/introductions.vtt" srclang="en" label="English" default></video><p>${t('Text alternative: first identify yourself: “I am Alex.” Then name your work: “I work on the payments team.”', 'Alternativa textual: primeiro identifique-se: “I am Alex.” Depois indique seu trabalho: “I work on the payments team.”')}</p></details>` : ''}<p class="muted">${modeName(active.mode)}</p>${button('begin', t('Start with true or false →', 'Começar com verdadeiro ou falso →'))}${exit}</section>`;
    const feedback = active.answers.at(-1);
    if (active.phase === 'feedback') {
      const answer = question.options?.find(option => option.value === question.answer)?.label;
      return `${title}<section class="panel learning-panel">${progress}<div role="status" class="learning-feedback"><h2>${feedback.skipped ? t('Activity skipped', 'Atividade pulada') : feedback.correct === null ? t('Response saved · ungraded', 'Resposta salva · sem nota') : feedback.correct ? t('Correct', 'Correto') : t('Let’s review this', 'Vamos revisar')}</h2>${feedback.assisted ? `<p>${t('Completed with help; excluded from unassisted accuracy.', 'Feito com ajuda; excluído dos acertos sem ajuda.')}</p>` : ''}${!feedback.skipped ? `<p><strong>${t('Your response', 'Sua resposta')}:</strong> ${question.options ? loc(question.options.find(o => o.value === feedback.text).label) : e(feedback.text)}</p>` : ''}${question.answer ? `<p><strong>${t('Answer', 'Resposta')}:</strong> ${answer ? loc(answer) : e(question.answer)}</p><p>${question.id.endsWith(':tf') ? loc(unit.explanation) : loc(unit.rationale)}</p>` : `<p>${loc(unit.tip)}</p><p><strong>${t('Compare with an example; other answers can work.', 'Compare com um exemplo; outras respostas podem funcionar.')}</strong></p><p lang="en">${e(question.id.endsWith(':roleplay') ? unit.model : unit.example)}</p>`}${question.type === 'listen' ? `<p lang="en">${e(unit.example)}</p>` : ''}${!feedback.correct && feedback.confidence === 'confident' && feedback.correct !== null ? `<p>${t('You felt confident. Notice what changed in the correction before continuing.', 'Você estava confiante. Observe o que mudou na correção antes de continuar.')}</p>` : ''}</div><div class="form-actions">${button('continue', active.index + 1 === active.questions.length ? t('Complete lesson →', 'Concluir lição →') : t('Continue →', 'Continuar →'))}${button('bookmark', t('Save useful phrase', 'Salvar expressão útil'), `data-unit="${unit.id}"`, 'subtle')}</div>${exit}</section>`;
    }
    const choices = question.options ? `<fieldset class="choice-options"><legend>${t('Choose one answer', 'Escolha uma resposta')}</legend>${question.options.map(o => `<label class="choice-option"><input type="radio" name="answer" value="${e(o.value)}" required ${active.draft === o.value ? 'checked' : ''}><span>${loc(o.label)}</span></label>`).join('')}</fieldset>` : '';
    const order = question.type === 'order' ? `<div class="word-bank" role="group" aria-label="${t('Sentence parts', 'Partes da frase')}">${question.chunks.map((chunk, i) => button('chunk', e(chunk), `data-index="${i}"`, 'subtle')).join('')}${button('reset-sentence', t('Clear sentence', 'Limpar frase'), '', 'subtle')}</div>` : '';
    const textInput = !question.options ? `<label for="learning-answer">${question.type === 'listen' ? t('Missing phrase', 'Expressão que falta') : t('Your answer in English', 'Sua resposta em inglês')}</label><textarea id="learning-answer" name="answer" rows="3" maxlength="4000" required>${e(active.draft)}</textarea>` : '';
    const previous = active.answers.filter(a => a.type === 'write');
    return `${title}<section class="panel learning-panel">${progress}<span class="eyebrow">${loc(question.label)}</span><h2 lang="en">${e(question.prompt)}</h2>${question.type === 'listen' ? audio(unit) : ''}${active.assisted ? `<aside class="worked-example"><p>${loc(unit.explanation)}</p><p lang="en">${e(unit.example)}</p></aside>` : button('help', question.type === 'listen' ? t('Read transcript · counts as help', 'Ler transcrição · conta como ajuda') : t('Show explanation · counts as help', 'Ver explicação · conta como ajuda'), '', 'subtle')}${question.id.endsWith(':rewrite') && previous.length ? `<details open><summary>${t('Your earlier response', 'Sua resposta anterior')}</summary><p>${e(previous[0].text)}</p></details>` : ''}<form id="learning-answer-form">${choices}${order}${textInput}<label for="learning-confidence">${t('How sure are you? (self-reflection)', 'Qual sua confiança? (autorreflexão)')}</label><select id="learning-confidence" name="confidence"><option value="unsure">${t('Still thinking', 'Ainda tenho dúvida')}</option><option value="confident">${t('Confident', 'Confiante')}</option></select><div class="form-actions"><button class="button primary" type="submit">${t('Check and reflect →', 'Conferir e refletir →')}</button>${question.optional ? button('skip', t('Skip listening', 'Pular escuta'), '', 'subtle') : ''}</div></form>${exit}</section>`;
  }
  const recommended = recommendUnits(state)[0];
  const latest = learning.runs[0];
  const results = latest?.answers.filter(a => a.correct !== null && !a.assisted && !a.skipped) ?? [];
  const filtered = units.filter(u => `${u.title.en} ${u.title['pt-BR']} ${u.skill.en} ${u.skill['pt-BR']}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return `${title}<section class="learning-banner"><div><span class="eyebrow">${t('SUGGESTED NEXT STEP', 'PRÓXIMO PASSO SUGERIDO')}</span><h2>${loc(recommended.title)}</h2><p>${metrics.due ? t('A review is due. Retrieve it before seeing the explanation again.', 'Há revisão pendente. Tente lembrar antes de rever a explicação.') : t('Build a habit with a short lesson. You choose when to move to writing.', 'Crie um hábito com uma lição curta. Você escolhe quando avançar para a escrita.')}</p></div><div class="form-actions">${button('start', t('Start lesson →', 'Iniciar lição →'), `data-unit="${recommended.id}"`)}${button('mixed', t('Mixed retrieval', 'Revisão misturada'), `data-unit="${recommended.id}"`, 'subtle')}</div></section>
  <div class="stats learning-stats"><div class="stat"><span>${t('DAYS THIS WEEK', 'DIAS NESTA SEMANA')}</span><strong>${metrics.days} / ${learning.goal}</strong><small>${t('Flexible goal; no streak penalty', 'Meta flexível; sem punição por pausas')}</small></div><div class="stat"><span>${t('LESSONS EXPLORED', 'LIÇÕES EXPLORADAS')}</span><strong>${metrics.studied} / ${units.length}</strong><small>${t('Activity, not proficiency', 'Atividade, não proficiência')}</small></div><div class="stat"><span>${t('REVIEWS DUE', 'REVISÕES PENDENTES')}</span><strong>${metrics.due}</strong><small>${t('Intervals: 1, 3, 7, 14, 30 days', 'Intervalos: 1, 3, 7, 14, 30 dias')}</small></div></div>
  ${latest ? `<section class="panel learning-summary"><h2>${t('Latest lesson', 'Última lição')}</h2><p>${results.filter(a => a.correct).length} / ${results.length} ${t('unassisted objective checks correct. Open responses are ungraded.', 'questões objetivas corretas sem ajuda. Respostas abertas não recebem nota.')}</p><p>${t('Incorrect items return sooner. For the next challenge, choose Guided or Applied below.', 'Itens incorretos voltam mais cedo. Para o próximo desafio, escolha Guiado ou Aplicação abaixo.')}</p><details><summary>${t('Review saved responses', 'Ver respostas salvas')}</summary>${latest.answers.map(a => `<div class="history-answer"><small>${loc(units.find(u => u.id === a.unitId).title)}</small><p>${a.skipped ? t('Skipped', 'Pulado') : e(a.type === 'choice' ? (a.id.endsWith(':tf') ? (a.text === 'true' ? (pt ? 'Verdadeiro' : 'True') : (pt ? 'Falso' : 'False')) : units.find(u => u.id === a.unitId).choices[Number(a.text)]) : a.text)}</p></div>`).join('')}</details></section>` : ''}
  <section class="panel learning-settings"><h2>${t('Make the plan yours', 'Ajuste seu plano')}</h2><form id="learning-preferences"><div><label for="learning-mode">${t('Practice mode', 'Modo de prática')}</label><select id="learning-mode" name="mode">${['recognition', 'guided', 'applied'].map(mode => `<option value="${mode}" ${mode === learning.mode ? 'selected' : ''}>${modeName(mode)}</option>`).join('')}</select></div><div><label for="learning-goal">${t('Days per week', 'Dias por semana')}</label><select id="learning-goal" name="goal">${[1,3,5,7].map(goal => `<option ${goal === learning.goal ? 'selected' : ''}>${goal}</option>`).join('')}</select></div><button class="button subtle" type="submit">${t('Save plan', 'Salvar plano')}</button></form><p class="muted">${t('Recognition → ordering and listening → guided writing → transfer and scripted dialogue. These are practice modes, not proficiency levels.', 'Reconhecimento → ordenação e escuta → escrita guiada → aplicação e diálogo com roteiro. São modos de prática, não níveis de proficiência.')}</p></section>
  <div class="section-title"><h2>${t('Lesson library', 'Biblioteca de lições')}</h2></div><form id="learning-search" class="learning-search"><label for="learning-query">${t('Find a topic', 'Encontre um tema')}</label><input id="learning-query" name="query" value="${e(query)}" maxlength="80"><button class="button subtle" type="submit">${t('Search', 'Buscar')}</button></form><div class="learning-grid">${filtered.map((unit, i) => { const record = learning.records[unit.id]; return `<article class="panel"><span class="eyebrow">${loc(unit.skill)}</span><h2>${loc(unit.title)}</h2><p>${loc(unit.explanation)}</p><small>${record ? `${t('Last objective checks', 'Últimas questões objetivas')}: ${record.correct}/${record.total} · ${t('Review', 'Revisão')}: ${e(new Intl.DateTimeFormat(language, { dateStyle: 'short' }).format(new Date(record.dueAt)))}` : t('New lesson', 'Lição nova')}</small><div class="form-actions">${button('start', t('Practice →', 'Praticar →'), `data-unit="${unit.id}"`)}</div></article>`; }).join('')}</div>${!filtered.length ? `<p>${t('No matching lessons. Try another topic.', 'Nenhuma lição encontrada. Tente outro tema.')}</p>` : ''}
  <p class="footnote">${t('Your answers stay on this device and are included in History → Export data. Goals and scheduling are product heuristics, not validated learning predictions.', 'Suas respostas ficam neste dispositivo e entram em Histórico → Exportar dados. Metas e agendamento são regras do produto, não previsões validadas de aprendizagem.')}</p>`;
}

export function renderLearningHistory(state, language, e) {
  const pt = language === 'pt-BR';
  const runs = learningState(state).runs;
  if (!runs.length) return '';
  return `<section class="panel learning-summary"><h2>${e(pt ? 'Histórico da trilha de aprendizagem' : 'Learning path history')}</h2><p>${runs.length} ${e(pt ? 'lições concluídas · respostas locais' : 'completed lessons · local answers')}</p>${runs.map(run => `<details class="history-item"><summary><strong>${e(run.mixed ? (pt ? 'Revisão misturada' : 'Mixed retrieval') : units.find(unit => unit.id === run.unitId)?.title[language] ?? run.unitId)}</strong><span>${e(new Intl.DateTimeFormat(language, {dateStyle:'medium'}).format(new Date(run.completedAt)))}</span></summary>${run.answers.map(answer => `<div class="history-answer"><small lang="en">${e(answer.prompt ?? answer.id)}</small><p>${e(answer.skipped ? (pt ? 'Atividade pulada' : 'Activity skipped') : answer.responseLabel ?? answer.text)}</p><small>${e(answer.assisted ? (pt ? 'Com ajuda' : 'With help') : answer.correct === null ? (pt ? 'Sem nota' : 'Ungraded') : answer.correct ? (pt ? 'Correto' : 'Correct') : (pt ? 'Revisar' : 'Review'))}</small></div>`).join('')}</details>`).join('')}</section>`;
}
